# Generated by Django 3.1.4 on 2021-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(default=None, max_length=50)),
                ('T_name', models.CharField(default=None, max_length=50)),
                ('profile', models.URLField(default=None, max_length=500)),
            ],
        ),
    ]
