# Generated by Django 3.1.4 on 2021-04-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=10, null=True)),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
            options={
                'ordering': ['batch'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='batch.batch')),
            ],
            options={
                'ordering': ['batch'],
            },
        ),
    ]
